export const LOGIN = 'LOGIN'
export const LOGIN_OK = 'LOGIN_OK'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_OK = 'LOGOUT_OK'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'