declare module 'redux'
declare module 'react-redux'
declare module 'redux-thunk'
declare module 'redux-logger'
declare module 'react-router'
declare module 'react-router-dom'
declare module 'react-router-redux'